; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2021-07-27 at 14:43:28

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z0.250 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X181.892 Y202.924 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X187.839 Y203.276 E2.01419 ; external small perimeter
G1 X190.507 Y208.602 E2.02839 ; external small perimeter
G1 X187.228 Y213.576 E2.04258 ; external small perimeter
G1 X181.281 Y213.224 E2.05678 ; external small perimeter
G1 X178.613 Y207.898 E2.07097 ; external small perimeter
G1 X181.793 Y203.074 E2.08474 ; external small perimeter
G1 E0.08474 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X182.350 Y205.672 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X182.139 Y205.659 E2.00060 ; infill
G1 X181.706 Y206.315 E2.00285 ; infill
G1 X183.847 Y204.175 E2.01151 ; infill
G1 X186.931 Y204.358 E2.02034 ; infill
G1 X180.893 Y210.395 E2.04475 ; infill
G1 X181.756 Y212.117 E2.05026 ; infill
G1 X182.400 Y212.155 E2.05210 ; infill
G1 X188.301 Y206.254 E2.07597 ; infill
G1 X189.037 Y207.722 E2.08066 ; infill
G1 X186.982 Y210.840 E2.09134 ; infill
G1 X185.484 Y212.338 E2.09740 ; infill
G1 Z1.450 F1800.000 ; move to next layer (1)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E2.12603 ; external small perimeter
G1 X190.899 Y208.626 E2.15466 ; external small perimeter
G1 X187.404 Y213.927 E2.18330 ; external small perimeter
G1 X181.065 Y213.552 E2.21193 ; external small perimeter
G1 X178.221 Y207.874 E2.24056 ; external small perimeter
G1 X181.617 Y202.723 E2.26839 ; external small perimeter
G1 X187.707 Y204.820 F1800.000 ; move to first infill point
G1 F1200.000
G1 X186.639 Y203.752 E2.28031 ; infill
G1 X183.843 Y203.586 E2.30243 ; infill
G1 X189.630 Y209.374 E2.36704 ; infill
G1 X188.584 Y210.959 E2.38203 ; infill
G1 X181.581 Y203.955 E2.46023 ; infill
G1 X180.536 Y205.541 E2.47523 ; infill
G1 X187.539 Y212.545 E2.55343 ; infill
G1 X187.220 Y213.029 E2.55800 ; infill
G1 X185.277 Y212.914 E2.57337 ; infill
G1 X179.490 Y207.126 E2.63799 ; infill
G1 X179.287 Y207.435 E2.64091 ; infill
G1 X181.413 Y211.680 E2.67839 ; infill
G1 X182.481 Y212.748 E2.69031 ; infill
G1 Z2.650 F1800.000 ; move to next layer (2)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E2.71894 ; external small perimeter
G1 X190.899 Y208.626 E2.74757 ; external small perimeter
G1 X187.404 Y213.927 E2.77621 ; external small perimeter
G1 X181.065 Y213.552 E2.80484 ; external small perimeter
G1 X178.221 Y207.874 E2.83347 ; external small perimeter
G1 X181.617 Y202.723 E2.86130 ; external small perimeter
G1 X181.900 Y204.539 F1800.000 ; move to first infill point
G1 F1200.000
G1 X182.967 Y203.471 E2.87284 ; infill
G1 X185.373 Y203.614 E2.89128 ; infill
G1 X179.686 Y209.301 E2.95279 ; infill
G1 X180.537 Y210.999 E2.96731 ; infill
G1 X187.732 Y203.803 E3.04514 ; infill
G1 X188.583 Y205.501 E3.05966 ; infill
G1 X181.388 Y212.697 E3.13749 ; infill
G1 X181.413 Y212.748 E3.13793 ; infill
G1 X183.747 Y212.886 E3.15581 ; infill
G1 X189.434 Y207.199 E3.21732 ; infill
G1 X189.833 Y207.997 E3.22414 ; infill
G1 X187.221 Y211.961 E3.26045 ; infill
G1 X186.153 Y213.029 E3.27200 ; infill
M106 S244.8 ; enable fan
G1 Z3.850 F1800.000 ; move to next layer (3)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E3.30064 ; external small perimeter
G1 X190.899 Y208.626 E3.32927 ; external small perimeter
G1 X187.404 Y213.927 E3.35790 ; external small perimeter
G1 X181.065 Y213.552 E3.38654 ; external small perimeter
G1 X178.221 Y207.874 E3.41517 ; external small perimeter
G1 X181.617 Y202.723 E3.44299 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E3.46316 ; infill
G1 X182.922 Y203.532 E3.48742 ; infill
G1 X189.286 Y209.895 E3.55397 ; infill
G1 X188.062 Y211.752 E3.57041 ; infill
G1 X181.058 Y204.748 E3.64366 ; infill
G1 X179.834 Y206.605 E3.66011 ; infill
G1 X186.198 Y212.968 E3.72666 ; infill
G1 X182.923 Y212.774 E3.75092 ; infill
G1 X180.995 Y210.846 E3.77108 ; infill
M106 S242.25 ; enable fan
G1 Z5.050 F1800.000 ; move to next layer (4)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E3.79972 ; external small perimeter
G1 X190.899 Y208.626 E3.82835 ; external small perimeter
G1 X187.404 Y213.927 E3.85699 ; external small perimeter
G1 X181.065 Y213.552 E3.88562 ; external small perimeter
G1 X178.221 Y207.874 E3.91425 ; external small perimeter
G1 X181.617 Y202.723 E3.94207 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E3.95959 ; infill
G1 X179.287 Y208.503 E3.98922 ; infill
G1 X179.934 Y209.795 E3.99991 ; infill
G1 X186.074 Y203.655 E4.06412 ; infill
G1 X187.707 Y203.752 E4.07622 ; infill
G1 X188.158 Y204.652 E4.08366 ; infill
G1 X180.962 Y211.848 E4.15892 ; infill
G1 X181.413 Y212.748 E4.16636 ; infill
G1 X183.046 Y212.845 E4.17846 ; infill
G1 X189.186 Y206.705 E4.24267 ; infill
G1 X189.833 Y207.997 E4.25336 ; infill
G1 X187.628 Y211.343 E4.28300 ; infill
G1 X185.954 Y213.017 E4.30051 ; infill
M106 S244.8 ; enable fan
G1 Z6.250 F1800.000 ; move to next layer (5)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E4.32914 ; external small perimeter
G1 X190.899 Y208.626 E4.35777 ; external small perimeter
G1 X187.404 Y213.927 E4.38641 ; external small perimeter
G1 X181.065 Y213.552 E4.41504 ; external small perimeter
G1 X178.221 Y207.874 E4.44367 ; external small perimeter
G1 X181.617 Y202.723 E4.47150 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E4.49166 ; infill
G1 X182.922 Y203.532 E4.51592 ; infill
G1 X189.286 Y209.895 E4.58247 ; infill
G1 X188.062 Y211.752 E4.59892 ; infill
G1 X181.058 Y204.748 E4.67217 ; infill
G1 X179.834 Y206.605 E4.68861 ; infill
G1 X186.198 Y212.968 E4.75516 ; infill
G1 X182.923 Y212.774 E4.77942 ; infill
G1 X180.995 Y210.846 E4.79959 ; infill
M106 S242.25 ; enable fan
G1 Z7.450 F1800.000 ; move to next layer (6)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E4.82822 ; external small perimeter
G1 X190.899 Y208.626 E4.85686 ; external small perimeter
G1 X187.404 Y213.927 E4.88549 ; external small perimeter
G1 X181.065 Y213.552 E4.91412 ; external small perimeter
G1 X178.221 Y207.874 E4.94276 ; external small perimeter
G1 X181.617 Y202.723 E4.97058 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E4.98809 ; infill
G1 X179.287 Y208.503 E5.01772 ; infill
G1 X179.934 Y209.795 E5.02841 ; infill
G1 X186.074 Y203.655 E5.09263 ; infill
G1 X187.707 Y203.752 E5.10472 ; infill
G1 X188.158 Y204.652 E5.11217 ; infill
G1 X180.962 Y211.848 E5.18742 ; infill
G1 X181.413 Y212.748 E5.19487 ; infill
G1 X183.046 Y212.845 E5.20696 ; infill
G1 X189.186 Y206.705 E5.27118 ; infill
G1 X189.833 Y207.997 E5.28187 ; infill
G1 X187.628 Y211.343 E5.31150 ; infill
G1 X185.954 Y213.017 E5.32901 ; infill
M106 S244.8 ; enable fan
G1 Z8.650 F1800.000 ; move to next layer (7)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E5.35764 ; external small perimeter
G1 X190.899 Y208.626 E5.38628 ; external small perimeter
G1 X187.404 Y213.927 E5.41491 ; external small perimeter
G1 X181.065 Y213.552 E5.44354 ; external small perimeter
G1 X178.221 Y207.874 E5.47218 ; external small perimeter
G1 X181.617 Y202.723 E5.50000 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E5.52017 ; infill
G1 X182.922 Y203.532 E5.54442 ; infill
G1 X189.286 Y209.895 E5.61098 ; infill
G1 X188.062 Y211.752 E5.62742 ; infill
G1 X181.058 Y204.748 E5.70067 ; infill
G1 X179.834 Y206.605 E5.71712 ; infill
G1 X186.198 Y212.968 E5.78367 ; infill
G1 X182.923 Y212.774 E5.80793 ; infill
G1 X180.995 Y210.846 E5.82809 ; infill
M106 S242.25 ; enable fan
G1 Z9.850 F1800.000 ; move to next layer (8)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E5.85673 ; external small perimeter
G1 X190.899 Y208.626 E5.88536 ; external small perimeter
G1 X187.404 Y213.927 E5.91399 ; external small perimeter
G1 X181.065 Y213.552 E5.94263 ; external small perimeter
G1 X178.221 Y207.874 E5.97126 ; external small perimeter
G1 X181.617 Y202.723 E5.99908 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E6.01659 ; infill
G1 X179.287 Y208.503 E6.04623 ; infill
G1 X179.934 Y209.795 E6.05692 ; infill
G1 X186.074 Y203.655 E6.12113 ; infill
G1 X187.707 Y203.752 E6.13323 ; infill
G1 X188.158 Y204.652 E6.14067 ; infill
G1 X180.962 Y211.848 E6.21593 ; infill
G1 X181.413 Y212.748 E6.22337 ; infill
G1 X183.046 Y212.845 E6.23546 ; infill
G1 X189.186 Y206.705 E6.29968 ; infill
G1 X189.833 Y207.997 E6.31037 ; infill
G1 X187.628 Y211.343 E6.34000 ; infill
G1 X185.954 Y213.017 E6.35751 ; infill
M106 S244.8 ; enable fan
G1 Z11.050 F1800.000 ; move to next layer (9)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E6.38615 ; external small perimeter
G1 X190.899 Y208.626 E6.41478 ; external small perimeter
G1 X187.404 Y213.927 E6.44342 ; external small perimeter
G1 X181.065 Y213.552 E6.47205 ; external small perimeter
G1 X178.221 Y207.874 E6.50068 ; external small perimeter
G1 X181.617 Y202.723 E6.52850 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E6.54867 ; infill
G1 X182.922 Y203.532 E6.57293 ; infill
G1 X189.286 Y209.895 E6.63948 ; infill
G1 X188.062 Y211.752 E6.65593 ; infill
G1 X181.058 Y204.748 E6.72918 ; infill
G1 X179.834 Y206.605 E6.74562 ; infill
G1 X186.198 Y212.968 E6.81217 ; infill
G1 X182.923 Y212.774 E6.83643 ; infill
G1 X180.995 Y210.846 E6.85660 ; infill
M106 S242.25 ; enable fan
G1 Z12.250 F1800.000 ; move to next layer (10)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E6.88523 ; external small perimeter
G1 X190.899 Y208.626 E6.91386 ; external small perimeter
G1 X187.404 Y213.927 E6.94250 ; external small perimeter
G1 X181.065 Y213.552 E6.97113 ; external small perimeter
G1 X178.221 Y207.874 E6.99976 ; external small perimeter
G1 X181.617 Y202.723 E7.02759 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E7.04510 ; infill
G1 X179.287 Y208.503 E7.07473 ; infill
G1 X179.934 Y209.795 E7.08542 ; infill
G1 X186.074 Y203.655 E7.14964 ; infill
G1 X187.707 Y203.752 E7.16173 ; infill
G1 X188.158 Y204.652 E7.16918 ; infill
G1 X180.962 Y211.848 E7.24443 ; infill
G1 X181.413 Y212.748 E7.25187 ; infill
G1 X183.046 Y212.845 E7.26397 ; infill
G1 X189.186 Y206.705 E7.32818 ; infill
G1 X189.833 Y207.997 E7.33888 ; infill
G1 X187.628 Y211.343 E7.36851 ; infill
G1 X185.954 Y213.017 E7.38602 ; infill
M106 S244.8 ; enable fan
G1 Z13.450 F1800.000 ; move to next layer (11)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E7.41465 ; external small perimeter
G1 X190.899 Y208.626 E7.44329 ; external small perimeter
G1 X187.404 Y213.927 E7.47192 ; external small perimeter
G1 X181.065 Y213.552 E7.50055 ; external small perimeter
G1 X178.221 Y207.874 E7.52919 ; external small perimeter
G1 X181.617 Y202.723 E7.55701 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E7.57718 ; infill
G1 X182.922 Y203.532 E7.60143 ; infill
G1 X189.286 Y209.895 E7.66799 ; infill
G1 X188.062 Y211.752 E7.68443 ; infill
G1 X181.058 Y204.748 E7.75768 ; infill
G1 X179.834 Y206.605 E7.77412 ; infill
G1 X186.198 Y212.968 E7.84068 ; infill
G1 X182.923 Y212.774 E7.86493 ; infill
G1 X180.995 Y210.846 E7.88510 ; infill
M106 S242.25 ; enable fan
G1 Z14.650 F1800.000 ; move to next layer (12)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E7.91373 ; external small perimeter
G1 X190.899 Y208.626 E7.94237 ; external small perimeter
G1 X187.404 Y213.927 E7.97100 ; external small perimeter
G1 X181.065 Y213.552 E7.99963 ; external small perimeter
G1 X178.221 Y207.874 E8.02827 ; external small perimeter
G1 X181.617 Y202.723 E8.05609 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E8.07360 ; infill
G1 X179.287 Y208.503 E8.10323 ; infill
G1 X179.934 Y209.795 E8.11393 ; infill
G1 X186.074 Y203.655 E8.17814 ; infill
G1 X187.707 Y203.752 E8.19023 ; infill
G1 X188.158 Y204.652 E8.19768 ; infill
G1 X180.962 Y211.848 E8.27293 ; infill
G1 X181.413 Y212.748 E8.28038 ; infill
G1 X183.046 Y212.845 E8.29247 ; infill
G1 X189.186 Y206.705 E8.35669 ; infill
G1 X189.833 Y207.997 E8.36738 ; infill
G1 X187.628 Y211.343 E8.39701 ; infill
G1 X185.954 Y213.017 E8.41452 ; infill
M106 S244.8 ; enable fan
G1 Z15.850 F1800.000 ; move to next layer (13)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E8.44316 ; external small perimeter
G1 X190.899 Y208.626 E8.47179 ; external small perimeter
G1 X187.404 Y213.927 E8.50042 ; external small perimeter
G1 X181.065 Y213.552 E8.52906 ; external small perimeter
G1 X178.221 Y207.874 E8.55769 ; external small perimeter
G1 X181.617 Y202.723 E8.58551 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E8.60568 ; infill
G1 X182.922 Y203.532 E8.62994 ; infill
G1 X189.286 Y209.895 E8.69649 ; infill
G1 X188.062 Y211.752 E8.71293 ; infill
G1 X181.058 Y204.748 E8.78618 ; infill
G1 X179.834 Y206.605 E8.80263 ; infill
G1 X186.198 Y212.968 E8.86918 ; infill
G1 X182.923 Y212.774 E8.89344 ; infill
G1 X180.995 Y210.846 E8.91360 ; infill
M106 S242.25 ; enable fan
G1 Z17.050 F1800.000 ; move to next layer (14)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E8.94224 ; external small perimeter
G1 X190.899 Y208.626 E8.97087 ; external small perimeter
G1 X187.404 Y213.927 E8.99951 ; external small perimeter
G1 X181.065 Y213.552 E9.02814 ; external small perimeter
G1 X178.221 Y207.874 E9.05677 ; external small perimeter
G1 X181.617 Y202.723 E9.08459 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E9.10211 ; infill
G1 X179.287 Y208.503 E9.13174 ; infill
G1 X179.934 Y209.795 E9.14243 ; infill
G1 X186.074 Y203.655 E9.20664 ; infill
G1 X187.707 Y203.752 E9.21874 ; infill
G1 X188.158 Y204.652 E9.22618 ; infill
G1 X180.962 Y211.848 E9.30144 ; infill
G1 X181.413 Y212.748 E9.30888 ; infill
G1 X183.046 Y212.845 E9.32098 ; infill
G1 X189.186 Y206.705 E9.38519 ; infill
G1 X189.833 Y207.997 E9.39588 ; infill
G1 X187.628 Y211.343 E9.42552 ; infill
G1 X185.954 Y213.017 E9.44303 ; infill
M106 S244.8 ; enable fan
G1 Z18.250 F1800.000 ; move to next layer (15)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E9.47166 ; external small perimeter
G1 X190.899 Y208.626 E9.50029 ; external small perimeter
G1 X187.404 Y213.927 E9.52893 ; external small perimeter
G1 X181.065 Y213.552 E9.55756 ; external small perimeter
G1 X178.221 Y207.874 E9.58619 ; external small perimeter
G1 X181.617 Y202.723 E9.61402 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E9.63418 ; infill
G1 X182.922 Y203.532 E9.65844 ; infill
G1 X189.286 Y209.895 E9.72499 ; infill
G1 X188.062 Y211.752 E9.74144 ; infill
G1 X181.058 Y204.748 E9.81469 ; infill
G1 X179.834 Y206.605 E9.83113 ; infill
G1 X186.198 Y212.968 E9.89768 ; infill
G1 X182.923 Y212.774 E9.92194 ; infill
G1 X180.995 Y210.846 E9.94211 ; infill
M106 S242.25 ; enable fan
G1 Z19.450 F1800.000 ; move to next layer (16)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E9.97074 ; external small perimeter
G1 X190.899 Y208.626 E9.99938 ; external small perimeter
G1 X187.404 Y213.927 E10.02801 ; external small perimeter
G1 X181.065 Y213.552 E10.05664 ; external small perimeter
G1 X178.221 Y207.874 E10.08528 ; external small perimeter
G1 X181.617 Y202.723 E10.11310 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E10.13061 ; infill
G1 X179.287 Y208.503 E10.16024 ; infill
G1 X179.934 Y209.795 E10.17093 ; infill
G1 X186.074 Y203.655 E10.23515 ; infill
G1 X187.707 Y203.752 E10.24724 ; infill
G1 X188.158 Y204.652 E10.25469 ; infill
G1 X180.962 Y211.848 E10.32994 ; infill
G1 X181.413 Y212.748 E10.33739 ; infill
G1 X183.046 Y212.845 E10.34948 ; infill
G1 X189.186 Y206.705 E10.41370 ; infill
G1 X189.833 Y207.997 E10.42439 ; infill
G1 X187.628 Y211.343 E10.45402 ; infill
G1 X185.954 Y213.017 E10.47153 ; infill
M106 S244.8 ; enable fan
G1 Z20.650 F1800.000 ; move to next layer (17)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E10.50016 ; external small perimeter
G1 X190.899 Y208.626 E10.52880 ; external small perimeter
G1 X187.404 Y213.927 E10.55743 ; external small perimeter
G1 X181.065 Y213.552 E10.58606 ; external small perimeter
G1 X178.221 Y207.874 E10.61470 ; external small perimeter
G1 X181.617 Y202.723 E10.64252 ; external small perimeter
G1 X188.125 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.197 Y203.726 E10.66269 ; infill
G1 X182.922 Y203.532 E10.68694 ; infill
G1 X189.286 Y209.895 E10.75350 ; infill
G1 X188.062 Y211.752 E10.76994 ; infill
G1 X181.058 Y204.748 E10.84319 ; infill
G1 X179.834 Y206.605 E10.85964 ; infill
G1 X186.198 Y212.968 E10.92619 ; infill
G1 X182.923 Y212.774 E10.95045 ; infill
G1 X180.995 Y210.846 E10.97061 ; infill
M106 S242.25 ; enable fan
G1 Z21.850 F1800.000 ; move to next layer (18)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E10.99925 ; external small perimeter
G1 X190.899 Y208.626 E11.02788 ; external small perimeter
G1 X187.404 Y213.927 E11.05651 ; external small perimeter
G1 X181.065 Y213.552 E11.08515 ; external small perimeter
G1 X178.221 Y207.874 E11.11378 ; external small perimeter
G1 X181.617 Y202.723 E11.14160 ; external small perimeter
G1 X183.166 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.492 Y205.157 E11.15911 ; infill
G1 X179.287 Y208.503 E11.18875 ; infill
G1 X179.934 Y209.795 E11.19944 ; infill
G1 X186.074 Y203.655 E11.26365 ; infill
G1 X187.707 Y203.752 E11.27575 ; infill
G1 X188.158 Y204.652 E11.28319 ; infill
G1 X180.962 Y211.848 E11.35845 ; infill
G1 X181.413 Y212.748 E11.36589 ; infill
G1 X183.046 Y212.845 E11.37798 ; infill
G1 X189.186 Y206.705 E11.44220 ; infill
G1 X189.833 Y207.997 E11.45289 ; infill
G1 X187.628 Y211.343 E11.48252 ; infill
G1 X185.954 Y213.017 E11.50003 ; infill
M106 S249.9 ; enable fan
G1 Z23.050 F1800.000 ; move to next layer (19)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E11.52867 ; external small perimeter
G1 X190.899 Y208.626 E11.55730 ; external small perimeter
G1 X187.404 Y213.927 E11.58594 ; external small perimeter
G1 X181.065 Y213.552 E11.61457 ; external small perimeter
G1 X178.221 Y207.874 E11.64320 ; external small perimeter
G1 X181.617 Y202.723 E11.67102 ; external small perimeter
G1 X187.707 Y204.820 F1800.000 ; move to first infill point
G1 F1200.000
G1 X186.639 Y203.752 E11.68295 ; infill
G1 X183.843 Y203.586 E11.70506 ; infill
G1 X189.630 Y209.374 E11.76968 ; infill
G1 X188.584 Y210.959 E11.78467 ; infill
G1 X181.581 Y203.955 E11.86287 ; infill
G1 X180.536 Y205.541 E11.87787 ; infill
G1 X187.539 Y212.545 E11.95607 ; infill
G1 X187.220 Y213.029 E11.96064 ; infill
G1 X185.277 Y212.914 E11.97601 ; infill
G1 X179.490 Y207.126 E12.04062 ; infill
G1 X179.287 Y207.435 E12.04354 ; infill
G1 X181.413 Y211.680 E12.08103 ; infill
G1 X182.481 Y212.748 E12.09295 ; infill
G1 Z24.250 F1800.000 ; move to next layer (20)
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.055 Y202.948 E12.12158 ; external small perimeter
G1 X190.899 Y208.626 E12.15021 ; external small perimeter
G1 X187.404 Y213.927 E12.17885 ; external small perimeter
G1 X181.065 Y213.552 E12.20748 ; external small perimeter
G1 X178.221 Y207.874 E12.23611 ; external small perimeter
G1 X181.617 Y202.723 E12.26394 ; external small perimeter
G1 X181.900 Y204.539 F1800.000 ; move to first infill point
G1 F1200.000
G1 X182.967 Y203.471 E12.27548 ; infill
G1 X185.373 Y203.614 E12.29392 ; infill
G1 X179.686 Y209.301 E12.35543 ; infill
G1 X180.537 Y210.999 E12.36995 ; infill
G1 X187.732 Y203.803 E12.44778 ; infill
G1 X188.583 Y205.501 E12.46230 ; infill
G1 X181.388 Y212.697 E12.54013 ; infill
G1 X181.413 Y212.748 E12.54057 ; infill
G1 X183.747 Y212.886 E12.55845 ; infill
G1 X189.434 Y207.199 E12.61996 ; infill
G1 X189.833 Y207.997 E12.62678 ; infill
G1 X187.221 Y211.961 E12.66309 ; infill
G1 X186.153 Y213.029 E12.67464 ; infill
M106 S237.15 ; enable fan
G1 Z25.450 F1800.000 ; move to next layer (21)
G1 E10.67464 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X181.716 Y202.573 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X188.055 Y202.948 E2.02863 ; external small perimeter
G1 X190.899 Y208.626 E2.05727 ; external small perimeter
G1 X187.404 Y213.927 E2.08590 ; external small perimeter
G1 X181.065 Y213.552 E2.11453 ; external small perimeter
G1 X178.221 Y207.874 E2.14317 ; external small perimeter
G1 X181.617 Y202.723 E2.17099 ; external small perimeter
G1 E0.17099 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X187.798 Y204.319 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F900.000
G1 X187.018 Y203.539 E2.00475 ; infill
G1 X185.494 Y203.449 E2.01132 ; infill
G1 X189.237 Y207.192 E2.03409 ; infill
G1 X190.116 Y208.946 E2.04253 ; infill
G1 X189.894 Y209.283 E2.04427 ; infill
G1 X183.970 Y203.359 E2.08032 ; infill
G1 X182.446 Y203.268 E2.08689 ; infill
G1 X189.324 Y210.147 E2.12874 ; infill
G1 X188.755 Y211.011 E2.13320 ; infill
G1 X181.505 Y203.761 E2.17731 ; infill
G1 X180.935 Y204.625 E2.18177 ; infill
G1 X188.185 Y211.875 E2.22588 ; infill
G1 X187.615 Y212.739 E2.23034 ; infill
G1 X180.365 Y205.489 E2.27445 ; infill
G1 X179.796 Y206.353 E2.27891 ; infill
G1 X186.674 Y213.232 E2.32076 ; infill
G1 X185.150 Y213.141 E2.32733 ; infill
G1 X179.226 Y207.217 E2.36338 ; infill
G1 X179.004 Y207.554 E2.36512 ; infill
G1 X179.883 Y209.308 E2.37356 ; infill
G1 X183.626 Y213.051 E2.39633 ; infill
G1 X182.102 Y212.961 E2.40290 ; infill
G1 X181.322 Y212.181 E2.40765 ; infill
G1 E0.40765 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 184.574775
; cog_y = 208.264474
; cog_z = 13.274609
; filament_length_m = 0.0113 
; filament_volume_cm3 = 0.0801
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.025
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = -0.1
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
