; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2021-07-27 at 14:43:28

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z0.250 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X188.860 Y203.994 F1800.000 ; move to first perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X180.734 Y203.512 E2.01106 ; perimeter
G1 Z1.450 F1800.000 ; move to next layer (1)
G1 X181.647 Y203.255 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X187.984 Y203.630 E2.02938 ; external perimeter
G1 X188.913 Y205.494 E2.03539 ; external perimeter

G1 F1200.000
G1 X190.828 Y209.338 E2.05737 ; external perimeter (bridge)
G1 X189.015 Y212.101 E2.07429 ; external perimeter (bridge)
G1 X179.623 Y211.544 E2.12247 ; external perimeter (bridge)
G1 X178.148 Y208.586 E2.13939 ; external perimeter (bridge)
G1 X180.504 Y204.996 E2.16137 ; external perimeter (bridge)

G1 F600.000
G1 X181.548 Y203.405 E2.16686 ; external perimeter
G1 E0.16686 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X187.853 Y205.015 F1800.000 ; move to first infill (bridge) point
G1 E2.00000 F2400.00000 ; unretract extruder 0

G1 F1200.000
G1 X181.613 Y204.645 E2.03689 ; infill (bridge)
G1 X180.428 Y206.450 E2.04962 ; infill (bridge)
G1 X188.816 Y206.947 E2.09920 ; infill (bridge)
G1 X189.779 Y208.879 E2.11193 ; infill (bridge)
G1 X179.244 Y208.254 E2.17420 ; infill (bridge)
G1 X178.994 Y208.636 E2.17689 ; infill (bridge)
G1 X179.753 Y210.160 E2.18693 ; infill (bridge)
G1 X189.049 Y210.711 E2.24187 ; infill (bridge)
G1 X181.262 Y210.249 E2.28789 ; infill (bridge)

G1 Z2.650 F1800.000 ; move to next layer (2)
G1 X181.654 Y203.136 F1800.000 ; move to first external perimeter point
G1 F600.000
G1 X187.991 Y203.512 E2.30621 ; external perimeter
G1 X190.835 Y209.219 E2.32462 ; external perimeter
G1 X188.149 Y213.312 E2.33874 ; external perimeter

G1 F1200.000
G1 X187.337 Y214.551 E2.34633 ; external perimeter (bridge)
G1 X181.000 Y214.175 E2.37883 ; external perimeter (bridge)
G1 X180.339 Y212.849 E2.38642 ; external perimeter (bridge)

G1 F600.000
G1 X178.155 Y208.468 E2.40055 ; external perimeter
G1 X181.555 Y203.287 E2.41843 ; external perimeter
G1 X182.907 Y204.035 F1800.000 ; move to first infill point
G1 F1200.000
G1 X181.839 Y205.103 E2.42646 ; infill
G1 X179.363 Y208.877 E2.45045 ; infill
G1 X180.750 Y208.960 E2.45784 ; infill
G1 X185.520 Y204.190 E2.49369 ; infill
G1 X187.641 Y204.316 E2.50498 ; infill
G1 X187.814 Y204.663 E2.50704 ; infill
G1 X183.362 Y209.114 E2.54050 ; infill
G1 X185.975 Y209.269 E2.55441 ; infill
G1 X188.734 Y206.510 E2.57515 ; infill
G1 X189.654 Y208.356 E2.58612 ; infill
G1 X188.587 Y209.424 E2.59414 ; infill
G1 X187.150 Y212.581 F1800.000 ; move to first infill (bridge) point

G1 F1200.000
G1 X186.081 Y213.650 E2.60540 ; infill (bridge)

G1 E0.60540 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X183.282 Y213.485 F1800.000 ; move to first infill (bridge) point
G1 E2.00000 F2400.00000 ; unretract extruder 0

G1 F1200.000
G1 X186.831 Y209.936 E2.03736 ; infill (bridge)
G1 X184.032 Y209.770 E2.05824 ; infill (bridge)
G1 X181.045 Y212.757 E2.08969 ; infill (bridge)
G1 X180.059 Y210.778 E2.10615 ; infill (bridge)
G1 X181.233 Y209.604 E2.11851 ; infill (bridge)

M106 S249.9 ; enable fan
G1 Z3.850 F1800.000 ; move to next layer (3)
G1 X181.661 Y203.018 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X187.998 Y203.394 E2.13683 ; external small perimeter
G1 X190.842 Y209.101 E2.15524 ; external small perimeter
G1 X187.344 Y214.432 E2.17364 ; external small perimeter
G1 X181.007 Y214.057 E2.19196 ; external small perimeter
G1 X178.163 Y208.349 E2.21036 ; external small perimeter
G1 X181.562 Y203.168 E2.22825 ; external small perimeter
G1 X187.648 Y205.265 F1800.000 ; move to first infill point
G1 F1200.000
G1 X186.580 Y204.197 E2.23591 ; infill
G1 X183.771 Y204.031 E2.25019 ; infill
G1 X189.581 Y209.841 E2.29189 ; infill
G1 X188.534 Y211.436 E2.30157 ; infill
G1 X181.517 Y204.419 E2.35194 ; infill
G1 X180.470 Y206.014 E2.36162 ; infill
G1 X187.487 Y213.032 E2.41199 ; infill
G1 X187.158 Y213.534 E2.41504 ; infill
G1 X185.233 Y213.420 E2.42482 ; infill
G1 X179.423 Y207.610 E2.46652 ; infill
G1 X179.226 Y207.910 E2.46834 ; infill
G1 X181.356 Y212.185 E2.49258 ; infill
G1 X182.424 Y213.253 E2.50025 ; infill
G1 Z5.050 F1800.000 ; move to next layer (4)
G1 X181.668 Y202.900 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.005 Y203.275 E2.51857 ; external small perimeter
G1 X190.849 Y208.983 E2.53697 ; external small perimeter
G1 X187.351 Y214.314 E2.55537 ; external small perimeter
G1 X181.014 Y213.939 E2.57369 ; external small perimeter
G1 X178.170 Y208.231 E2.59210 ; external small perimeter
G1 X181.569 Y203.050 E2.60998 ; external small perimeter
G1 X181.854 Y204.866 F1800.000 ; move to first infill point
G1 F1200.000
G1 X182.921 Y203.798 E2.61740 ; infill
G1 X185.337 Y203.942 E2.62929 ; infill
G1 X179.627 Y209.651 E2.66897 ; infill
G1 X180.478 Y211.359 E2.67834 ; infill
G1 X187.689 Y204.148 E2.72845 ; infill
G1 X188.540 Y205.855 E2.73783 ; infill
G1 X181.329 Y213.066 E2.78794 ; infill
G1 X181.364 Y213.135 E2.78832 ; infill
G1 X183.682 Y213.272 E2.79973 ; infill
G1 X189.391 Y207.563 E2.83941 ; infill
G1 X189.785 Y208.354 E2.84375 ; infill
G1 X187.165 Y212.347 E2.86722 ; infill
G1 X186.097 Y213.415 E2.87465 ; infill
M106 S242.25 ; enable fan
G1 Z6.250 F1800.000 ; move to next layer (5)
G1 X181.675 Y202.781 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.012 Y203.157 E2.89297 ; external small perimeter
G1 X190.856 Y208.864 E2.91137 ; external small perimeter
G1 X187.358 Y214.196 E2.92977 ; external small perimeter
G1 X181.021 Y213.820 E2.94809 ; external small perimeter
G1 X178.177 Y208.113 E2.96649 ; external small perimeter
G1 X181.576 Y202.932 E2.98438 ; external small perimeter
G1 X181.218 Y210.569 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.438 Y213.017 E2.99732 ; infill
G1 X183.743 Y213.094 E3.00351 ; infill
G1 X180.151 Y209.501 E3.02756 ; infill
G1 X179.240 Y207.674 E3.03722 ; infill
G1 X180.097 Y206.368 E3.04462 ; infill
G1 X187.018 Y213.288 E3.09094 ; infill
G1 X187.172 Y213.297 E3.09167 ; infill
G1 X188.335 Y211.525 E3.10170 ; infill
G1 X181.318 Y204.508 E3.14867 ; infill
G1 X181.861 Y203.680 E3.15335 ; infill
G1 X183.678 Y203.788 E3.16197 ; infill
G1 X189.555 Y209.665 E3.20131 ; infill
G1 Z7.450 F1800.000 ; move to next layer (6)
G1 X181.682 Y202.663 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.019 Y203.039 E3.21963 ; external small perimeter
G1 X190.863 Y208.746 E3.23803 ; external small perimeter
G1 X187.365 Y214.078 E3.25644 ; external small perimeter
G1 X181.028 Y213.702 E3.27476 ; external small perimeter
G1 X178.184 Y207.995 E3.29316 ; external small perimeter
G1 X181.583 Y202.814 E3.31104 ; external small perimeter
G1 X184.447 Y204.782 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.868 Y204.629 E3.32327 ; infill
G1 X179.247 Y208.623 E3.34588 ; infill
G1 X179.699 Y209.530 E3.35068 ; infill
G1 X185.515 Y203.715 E3.38961 ; infill
G1 X187.669 Y203.842 E3.39982 ; infill
G1 X187.935 Y204.375 E3.40264 ; infill
G1 X180.724 Y211.586 E3.45090 ; infill
G1 X181.378 Y212.898 E3.45784 ; infill
G1 X182.430 Y212.961 E3.46283 ; infill
G1 X188.959 Y206.431 E3.50653 ; infill
G1 X189.799 Y208.118 E3.51545 ; infill
G1 X188.743 Y209.728 E3.52456 ; infill
G1 X185.338 Y213.133 E3.54736 ; infill
M106 S244.8 ; enable fan
G1 Z8.650 F1800.000 ; move to next layer (7)
G1 X181.689 Y202.545 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.026 Y202.920 E3.56568 ; external small perimeter
G1 X190.870 Y208.628 E3.58408 ; external small perimeter
G1 X187.372 Y213.959 E3.60248 ; external small perimeter
G1 X181.035 Y213.584 E3.62080 ; external small perimeter
G1 X178.191 Y207.876 E3.63921 ; external small perimeter
G1 X181.590 Y202.695 E3.65709 ; external small perimeter
G1 X181.481 Y210.832 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.452 Y212.780 E3.66739 ; infill
G1 X183.491 Y212.842 E3.67232 ; infill
G1 X180.414 Y209.764 E3.69291 ; infill
G1 X179.254 Y207.437 E3.70522 ; infill
G1 X180.012 Y206.282 E3.71176 ; infill
G1 X186.765 Y213.036 E3.75696 ; infill
G1 X187.186 Y213.061 E3.75896 ; infill
G1 X188.250 Y211.440 E3.76813 ; infill
G1 X181.232 Y204.422 E3.81510 ; infill
G1 X181.875 Y203.444 E3.82064 ; infill
G1 X183.426 Y203.536 E3.82800 ; infill
G1 X189.470 Y209.580 E3.86845 ; infill
M106 S242.25 ; enable fan
G1 Z9.850 F1800.000 ; move to next layer (8)
G1 X181.696 Y202.427 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.033 Y202.802 E3.88677 ; external small perimeter
G1 X190.877 Y208.510 E3.90518 ; external small perimeter
G1 X187.379 Y213.841 E3.92358 ; external small perimeter
G1 X181.042 Y213.465 E3.94190 ; external small perimeter
G1 X178.198 Y207.758 E3.96030 ; external small perimeter
G1 X181.597 Y202.577 E3.97818 ; external small perimeter
G1 X184.671 Y204.558 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.882 Y204.393 E3.99141 ; infill
G1 X179.261 Y208.386 E4.01402 ; infill
G1 X179.787 Y209.442 E4.01960 ; infill
G1 X185.739 Y203.491 E4.05944 ; infill
G1 X187.683 Y203.606 E4.06866 ; infill
G1 X188.023 Y204.287 E4.07226 ; infill
G1 X180.812 Y211.498 E4.12053 ; infill
G1 X181.392 Y212.662 E4.12668 ; infill
G1 X182.654 Y212.736 E4.13266 ; infill
G1 X189.047 Y206.343 E4.17546 ; infill
G1 X189.813 Y207.881 E4.18359 ; infill
G1 X188.332 Y210.138 E4.19637 ; infill
G1 X185.562 Y212.909 E4.21491 ; infill
M106 S244.8 ; enable fan
G1 Z11.050 F1800.000 ; move to next layer (9)
G1 X181.703 Y202.308 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.040 Y202.684 E4.23323 ; external small perimeter
G1 X190.884 Y208.391 E4.25163 ; external small perimeter
G1 X187.386 Y213.723 E4.27004 ; external small perimeter
G1 X181.049 Y213.347 E4.28836 ; external small perimeter
G1 X178.205 Y207.640 E4.30676 ; external small perimeter
G1 X181.604 Y202.459 E4.32464 ; external small perimeter
G1 X187.853 Y204.882 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.448 Y203.477 E4.33405 ; infill
G1 X183.174 Y203.283 E4.34957 ; infill
G1 X189.385 Y209.494 E4.39115 ; infill
G1 X188.164 Y211.354 E4.40168 ; infill
G1 X181.147 Y204.337 E4.44865 ; infill
G1 X179.927 Y206.197 E4.45917 ; infill
G1 X186.513 Y212.783 E4.50326 ; infill
G1 X183.239 Y212.589 E4.51878 ; infill
G1 X180.677 Y210.027 E4.53593 ; infill
M106 S242.25 ; enable fan
G1 Z12.250 F1800.000 ; move to next layer (10)
G1 X181.710 Y202.190 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.047 Y202.566 E4.55425 ; external small perimeter
G1 X190.891 Y208.273 E4.57266 ; external small perimeter
G1 X187.393 Y213.604 E4.59106 ; external small perimeter
G1 X181.056 Y213.229 E4.60938 ; external small perimeter
G1 X178.212 Y207.521 E4.62778 ; external small perimeter
G1 X181.611 Y202.340 E4.64567 ; external small perimeter
G1 X183.055 Y203.094 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.710 Y204.440 E4.65467 ; infill
G1 X179.275 Y208.150 E4.67567 ; infill
G1 X179.875 Y209.354 E4.68204 ; infill
G1 X185.963 Y203.267 E4.72279 ; infill
G1 X187.697 Y203.369 E4.73101 ; infill
G1 X188.111 Y204.199 E4.73540 ; infill
G1 X180.900 Y211.410 E4.78367 ; infill
G1 X181.406 Y212.425 E4.78903 ; infill
G1 X182.878 Y212.512 E4.79601 ; infill
G1 X189.135 Y206.255 E4.83790 ; infill
G1 X189.827 Y207.645 E4.84524 ; infill
G1 X187.921 Y210.549 E4.86169 ; infill
G1 X185.786 Y212.685 E4.87598 ; infill
M106 S244.8 ; enable fan
G1 Z13.450 F1800.000 ; move to next layer (11)
G1 X181.717 Y202.072 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.054 Y202.447 E4.89430 ; external small perimeter
G1 X190.898 Y208.155 E4.91270 ; external small perimeter
G1 X187.400 Y213.486 E4.93111 ; external small perimeter
G1 X181.063 Y213.111 E4.94943 ; external small perimeter
G1 X178.219 Y207.403 E4.96783 ; external small perimeter
G1 X181.618 Y202.222 E4.98571 ; external small perimeter
G1 X188.116 Y205.145 F1800.000 ; move to first infill point
G1 F600.000
G1 X186.196 Y203.225 E4.99857 ; infill
G1 X182.921 Y203.031 E5.01409 ; infill
G1 X189.299 Y209.409 E5.05679 ; infill
G1 X188.079 Y211.269 E5.06731 ; infill
G1 X181.062 Y204.252 E5.11428 ; infill
G1 X179.841 Y206.112 E5.12481 ; infill
G1 X186.261 Y212.531 E5.16778 ; infill
G1 X182.986 Y212.337 E5.18330 ; infill
G1 X180.940 Y210.290 E5.19700 ; infill
M106 S242.25 ; enable fan
G1 Z14.650 F1800.000 ; move to next layer (12)
G1 X181.724 Y201.953 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.061 Y202.329 E5.21532 ; external small perimeter
G1 X190.905 Y208.036 E5.23372 ; external small perimeter
G1 X187.407 Y213.368 E5.25213 ; external small perimeter
G1 X181.070 Y212.992 E5.27045 ; external small perimeter
G1 X178.226 Y207.285 E5.28885 ; external small perimeter
G1 X181.625 Y202.104 E5.30673 ; external small perimeter
G1 X183.279 Y202.870 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.299 Y204.850 E5.31999 ; infill
G1 X179.289 Y207.913 E5.33733 ; infill
G1 X179.963 Y209.266 E5.34448 ; infill
G1 X186.187 Y203.042 E5.38614 ; infill
G1 X187.711 Y203.133 E5.39337 ; infill
G1 X188.199 Y204.111 E5.39854 ; infill
G1 X180.988 Y211.322 E5.44681 ; infill
G1 X181.420 Y212.189 E5.45139 ; infill
G1 X183.102 Y212.288 E5.45937 ; infill
G1 X189.223 Y206.167 E5.50034 ; infill
G1 X189.841 Y207.408 E5.50690 ; infill
G1 X187.511 Y210.960 E5.52700 ; infill
G1 X186.010 Y212.461 E5.53705 ; infill
M106 S244.8 ; enable fan
G1 Z15.850 F1800.000 ; move to next layer (13)
G1 X181.731 Y201.835 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.068 Y202.211 E5.55537 ; external small perimeter
G1 X190.912 Y207.918 E5.57377 ; external small perimeter
G1 X187.414 Y213.250 E5.59218 ; external small perimeter
G1 X181.077 Y212.874 E5.61050 ; external small perimeter
G1 X178.233 Y207.167 E5.62890 ; external small perimeter
G1 X181.632 Y201.986 E5.64678 ; external small perimeter
G1 X188.379 Y205.408 F1800.000 ; move to first infill point
G1 F600.000
G1 X185.943 Y202.973 E5.66309 ; infill
G1 X182.669 Y202.779 E5.67861 ; infill
G1 X189.214 Y209.324 E5.72242 ; infill
G1 X187.994 Y211.184 E5.73295 ; infill
G1 X180.977 Y204.167 E5.77992 ; infill
G1 X179.756 Y206.027 E5.79045 ; infill
G1 X186.008 Y212.279 E5.83230 ; infill
G1 X182.734 Y212.084 E5.84782 ; infill
G1 X181.203 Y210.553 E5.85807 ; infill
G1 Z17.050 F1800.000 ; move to next layer (14)
G1 X181.738 Y201.717 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.075 Y202.092 E5.87639 ; external small perimeter
G1 X190.919 Y207.800 E5.89479 ; external small perimeter
G1 X187.421 Y213.131 E5.91320 ; external small perimeter
G1 X181.084 Y212.756 E5.93152 ; external small perimeter
G1 X178.240 Y207.048 E5.94992 ; external small perimeter
G1 X181.639 Y201.867 E5.96780 ; external small perimeter
G1 X182.436 Y203.714 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.924 Y203.683 E5.97023 ; infill
G1 X180.888 Y205.261 E5.97916 ; infill
G1 X183.503 Y202.646 E5.99667 ; infill
G1 X186.411 Y202.818 E6.01046 ; infill
G1 X180.051 Y209.178 E6.05303 ; infill
G1 X181.076 Y211.234 E6.06390 ; infill
G1 X188.287 Y204.023 E6.11216 ; infill
G1 X189.311 Y206.079 E6.12303 ; infill
G1 X183.326 Y212.064 E6.16309 ; infill
M106 S242.25 ; enable fan
G1 Z18.250 F1800.000 ; move to next layer (15)
G1 X181.745 Y201.599 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.082 Y201.974 E6.18141 ; external small perimeter
G1 X190.926 Y207.682 E6.19982 ; external small perimeter
G1 X187.428 Y213.013 E6.21822 ; external small perimeter
G1 X181.091 Y212.637 E6.23654 ; external small perimeter
G1 X178.247 Y206.930 E6.25494 ; external small perimeter
G1 X181.646 Y201.749 E6.27283 ; external small perimeter
G1 X180.738 Y207.009 F1800.000 ; move to first infill point
G1 F600.000
G1 X180.378 Y207.559 E6.27594 ; infill
G1 X182.508 Y211.834 E6.29855 ; infill
G1 X185.756 Y212.026 E6.31395 ; infill
G1 X179.671 Y205.941 E6.35467 ; infill
G1 X180.891 Y204.081 E6.36520 ; infill
G1 X187.908 Y211.098 E6.41217 ; infill
G1 X189.129 Y209.239 E6.42270 ; infill
G1 X182.416 Y202.526 E6.46763 ; infill
G1 X185.691 Y202.720 E6.48316 ; infill
G1 X188.642 Y205.671 E6.50291 ; infill
M106 S244.8 ; enable fan
G1 Z19.450 F1800.000 ; move to next layer (16)
G1 X181.752 Y201.480 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.089 Y201.856 E6.52123 ; external small perimeter
G1 X190.933 Y207.563 E6.53963 ; external small perimeter
G1 X187.435 Y212.895 E6.55803 ; external small perimeter
G1 X181.098 Y212.519 E6.57635 ; external small perimeter
G1 X178.254 Y206.812 E6.59476 ; external small perimeter
G1 X181.653 Y201.631 E6.61264 ; external small perimeter
G1 X182.660 Y203.489 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.938 Y203.447 E6.61607 ; infill
G1 X180.478 Y205.672 E6.62866 ; infill
G1 X183.728 Y202.422 E6.65041 ; infill
G1 X186.635 Y202.594 E6.66420 ; infill
G1 X180.139 Y209.090 E6.70768 ; infill
G1 X181.164 Y211.146 E6.71855 ; infill
G1 X188.375 Y203.935 E6.76682 ; infill
G1 X189.399 Y205.991 E6.77769 ; infill
G1 X183.550 Y211.840 E6.81684 ; infill
M106 S242.25 ; enable fan
G1 Z20.650 F1800.000 ; move to next layer (17)
G1 X181.759 Y201.362 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.096 Y201.738 E6.83516 ; external small perimeter
G1 X190.940 Y207.445 E6.85356 ; external small perimeter
G1 X187.442 Y212.776 E6.87197 ; external small perimeter
G1 X181.105 Y212.401 E6.89029 ; external small perimeter
G1 X178.261 Y206.694 E6.90869 ; external small perimeter
G1 X181.660 Y201.513 E6.92657 ; external small perimeter
G1 X180.653 Y206.924 F1800.000 ; move to first infill point
G1 F600.000
G1 X180.392 Y207.322 E6.92883 ; infill
G1 X182.522 Y211.597 E6.95144 ; infill
G1 X185.504 Y211.774 E6.96557 ; infill
G1 X179.586 Y205.856 E7.00518 ; infill
G1 X180.806 Y203.996 E7.01571 ; infill
G1 X187.823 Y211.013 E7.06268 ; infill
G1 X189.044 Y209.153 E7.07321 ; infill
G1 X182.164 Y202.274 E7.11926 ; infill
G1 X185.438 Y202.468 E7.13478 ; infill
G1 X188.905 Y205.934 E7.15798 ; infill
M106 S244.8 ; enable fan
G1 Z21.850 F1800.000 ; move to next layer (18)
G1 X181.766 Y201.244 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.103 Y201.619 E7.17630 ; external small perimeter
G1 X190.947 Y207.327 E7.19471 ; external small perimeter
G1 X187.449 Y212.658 E7.21311 ; external small perimeter
G1 X181.112 Y212.283 E7.23143 ; external small perimeter
G1 X178.268 Y206.575 E7.24983 ; external small perimeter
G1 X181.667 Y201.394 E7.26772 ; external small perimeter
G1 X182.884 Y203.265 F1800.000 ; move to first infill point
G1 F600.000
G1 X181.952 Y203.210 E7.27214 ; infill
G1 X180.067 Y206.082 E7.28840 ; infill
G1 X183.952 Y202.198 E7.31440 ; infill
G1 X186.860 Y202.370 E7.32819 ; infill
G1 X180.228 Y209.002 E7.37258 ; infill
G1 X181.252 Y211.058 E7.38345 ; infill
G1 X188.463 Y203.847 E7.43171 ; infill
G1 X189.487 Y205.903 E7.44259 ; infill
G1 X183.774 Y211.616 E7.48082 ; infill
M106 S249.9 ; enable fan
G1 Z23.050 F1800.000 ; move to next layer (19)
G1 X181.773 Y201.125 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.110 Y201.501 E7.49914 ; external small perimeter
G1 X190.954 Y207.208 E7.51755 ; external small perimeter
G1 X187.456 Y212.540 E7.53595 ; external small perimeter
G1 X181.119 Y212.164 E7.55427 ; external small perimeter
G1 X178.275 Y206.457 E7.57267 ; external small perimeter
G1 X181.674 Y201.276 E7.59056 ; external small perimeter
G1 X187.760 Y203.373 F1800.000 ; move to first infill point
G1 F1200.000
G1 X186.692 Y202.305 E7.59822 ; infill
G1 X183.884 Y202.138 E7.61250 ; infill
G1 X189.693 Y207.948 E7.65420 ; infill
G1 X188.646 Y209.544 E7.66388 ; infill
G1 X181.629 Y202.526 E7.71425 ; infill
G1 X180.582 Y204.122 E7.72393 ; infill
G1 X187.599 Y211.139 E7.77430 ; infill
G1 X187.270 Y211.641 E7.77735 ; infill
G1 X185.345 Y211.527 E7.78713 ; infill
G1 X179.535 Y205.717 E7.82883 ; infill
G1 X179.338 Y206.018 E7.83065 ; infill
G1 X181.469 Y210.293 E7.85489 ; infill
G1 X182.536 Y211.360 E7.86256 ; infill
G1 Z24.250 F1800.000 ; move to next layer (20)
G1 X181.780 Y201.007 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.117 Y201.383 E7.88088 ; external small perimeter
G1 X190.961 Y207.090 E7.89928 ; external small perimeter
G1 X187.463 Y212.422 E7.91768 ; external small perimeter
G1 X181.126 Y212.046 E7.93600 ; external small perimeter
G1 X178.282 Y206.339 E7.95440 ; external small perimeter
G1 X181.681 Y201.158 E7.97229 ; external small perimeter
G1 X181.966 Y202.973 F1800.000 ; move to first infill point
G1 F1200.000
G1 X183.033 Y201.906 E7.97971 ; infill
G1 X185.449 Y202.049 E7.99160 ; infill
G1 X179.740 Y207.758 E8.03128 ; infill
G1 X180.168 Y208.618 E8.03599 ; infill
G1 X181.038 Y208.618 E8.04027 ; infill
G1 X180.638 Y209.419 E8.04467 ; infill
G1 X187.801 Y202.255 E8.09446 ; infill
G1 X188.652 Y203.963 E8.10383 ; infill
G1 X181.441 Y211.174 E8.15395 ; infill
G1 X181.476 Y211.242 E8.15432 ; infill
G1 X183.794 Y211.380 E8.16574 ; infill
G1 X189.503 Y205.670 E8.20541 ; infill
G1 X189.897 Y206.462 E8.20976 ; infill
G1 X187.277 Y210.455 E8.23323 ; infill
G1 X186.209 Y211.523 E8.24065 ; infill
M106 S237.15 ; enable fan
G1 Z25.450 F1800.000 ; move to next layer (21)
G1 E6.24065 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X181.787 Y200.889 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X188.124 Y201.264 E2.01832 ; external small perimeter
G1 X190.968 Y206.972 E2.03672 ; external small perimeter
G1 X187.470 Y212.303 E2.05513 ; external small perimeter
G1 X181.133 Y211.928 E2.07345 ; external small perimeter
G1 X178.289 Y206.220 E2.09185 ; external small perimeter
G1 X181.688 Y201.039 E2.10973 ; external small perimeter
G1 E0.10973 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X187.866 Y202.635 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F900.000
G1 X187.086 Y201.855 E2.00305 ; infill
G1 X185.556 Y201.765 E2.00729 ; infill
G1 X189.296 Y205.505 E2.02192 ; infill
G1 X190.187 Y207.292 E2.02744 ; infill
G1 X189.971 Y207.620 E2.02852 ; infill
G1 X184.025 Y201.674 E2.05177 ; infill
G1 X182.495 Y201.583 E2.05601 ; infill
G1 X189.401 Y208.489 E2.08302 ; infill
G1 X188.831 Y209.359 E2.08589 ; infill
G1 X181.567 Y202.095 E2.11430 ; infill
G1 X180.997 Y202.964 E2.11717 ; infill
G1 X188.260 Y210.228 E2.14558 ; infill
G1 X187.690 Y211.097 E2.14845 ; infill
G1 X180.426 Y203.834 E2.17686 ; infill
G1 X179.856 Y204.703 E2.17973 ; infill
G1 X186.762 Y211.609 E2.20674 ; infill
G1 X185.232 Y211.518 E2.21098 ; infill
G1 X179.285 Y205.572 E2.23423 ; infill
G1 X179.070 Y205.900 E2.23531 ; infill
G1 X179.961 Y207.687 E2.24083 ; infill
G1 X183.701 Y211.428 E2.25546 ; infill
G1 X182.171 Y211.337 E2.25970 ; infill
G1 X181.391 Y210.557 E2.26275 ; infill
M106 S255 ; enable fan
G1 Z26.650 F1800.000 ; move to next layer (22)
G1 X180.043 Y209.609 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.825 Y210.130 E2.28814 ; external small perimeter
G1 X187.477 Y212.185 E2.29523 ; external small perimeter
G1 X181.140 Y211.809 E2.31355 ; external small perimeter
G1 X180.124 Y209.770 E2.32013 ; external small perimeter
G1 X181.186 Y210.745 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.557 Y211.122 E2.33472 ; infill
G1 E0.33472 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 53.958081
; cog_y = 60.751801
; cog_z = 4.053101
; filament_length_m = 0.0075 
; filament_volume_cm3 = 0.0527
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.016
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = -0.1
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
