; generated by Slic3r 1.3.1-dev (Build (Unknown revision)) on 2021-07-27 at 14:43:28

; external perimeters extrusion width = 1.32mm (12.75mm^3/s)
; perimeters extrusion width = 1.26mm (12.03mm^3/s)
; infill extrusion width = 2.00mm (20.91mm^3/s)
; solid infill extrusion width = 2.00mm (41.82mm^3/s)
; top infill extrusion width = 1.26mm (18.04mm^3/s)

M107 ; disable fan
G92 E0 ; reset extrusion distance
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

; Filament gcode

M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 Z0.250 F1800.000 ; move to next layer (0)
G1 E-2.00000 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X182.762 Y202.924 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X188.709 Y203.276 E2.01107 ; external small perimeter
G1 X191.377 Y208.602 E2.02214 ; external small perimeter
G1 X188.098 Y213.576 E2.03322 ; external small perimeter
G1 X182.151 Y213.224 E2.04429 ; external small perimeter
G1 X179.483 Y207.898 E2.05536 ; external small perimeter
G1 X182.663 Y203.074 E2.06610 ; external small perimeter
G1 E0.06610 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X183.220 Y205.672 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X183.009 Y205.659 E2.00047 ; infill
G1 X182.576 Y206.315 E2.00222 ; infill
G1 X184.717 Y204.175 E2.00898 ; infill
G1 X187.801 Y204.358 E2.01587 ; infill
G1 X181.763 Y210.395 E2.03491 ; infill
G1 X182.626 Y212.117 E2.03920 ; infill
G1 X183.270 Y212.155 E2.04064 ; infill
G1 X189.171 Y206.254 E2.05925 ; infill
G1 X189.907 Y207.722 E2.06292 ; infill
G1 X187.852 Y210.840 E2.07125 ; infill
G1 X186.354 Y212.338 E2.07597 ; infill
G1 Z1.450 F1800.000 ; move to next layer (1)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E2.09830 ; external small perimeter
G1 X191.769 Y208.626 E2.12064 ; external small perimeter
G1 X188.274 Y213.927 E2.14297 ; external small perimeter
G1 X181.935 Y213.552 E2.16531 ; external small perimeter
G1 X179.091 Y207.874 E2.18764 ; external small perimeter
G1 X182.487 Y202.723 E2.20934 ; external small perimeter
G1 X188.577 Y204.820 F1800.000 ; move to first infill point
G1 F1200.000
G1 X187.509 Y203.752 E2.21864 ; infill
G1 X184.713 Y203.586 E2.23589 ; infill
G1 X190.500 Y209.374 E2.28629 ; infill
G1 X189.454 Y210.959 E2.29799 ; infill
G1 X182.451 Y203.955 E2.35898 ; infill
G1 X181.406 Y205.541 E2.37068 ; infill
G1 X188.409 Y212.545 E2.43167 ; infill
G1 X188.090 Y213.029 E2.43524 ; infill
G1 X186.147 Y212.914 E2.44723 ; infill
G1 X180.360 Y207.126 E2.49763 ; infill
G1 X180.157 Y207.435 E2.49991 ; infill
G1 X182.283 Y211.680 E2.52914 ; infill
G1 X183.351 Y212.748 E2.53844 ; infill
G1 Z2.650 F1800.000 ; move to next layer (2)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E2.56077 ; external small perimeter
G1 X191.769 Y208.626 E2.58311 ; external small perimeter
G1 X188.274 Y213.927 E2.60544 ; external small perimeter
G1 X181.935 Y213.552 E2.62778 ; external small perimeter
G1 X179.091 Y207.874 E2.65011 ; external small perimeter
G1 X182.487 Y202.723 E2.67181 ; external small perimeter
G1 X182.770 Y204.539 F1800.000 ; move to first infill point
G1 F1200.000
G1 X183.837 Y203.471 E2.68082 ; infill
G1 X186.243 Y203.614 E2.69520 ; infill
G1 X180.556 Y209.301 E2.74317 ; infill
G1 X181.407 Y210.999 E2.75450 ; infill
G1 X188.602 Y203.803 E2.81521 ; infill
G1 X189.453 Y205.501 E2.82654 ; infill
G1 X182.258 Y212.697 E2.88724 ; infill
G1 X182.283 Y212.748 E2.88758 ; infill
G1 X184.617 Y212.886 E2.90153 ; infill
G1 X190.304 Y207.199 E2.94951 ; infill
G1 X190.703 Y207.997 E2.95483 ; infill
G1 X188.091 Y211.961 E2.98315 ; infill
G1 X187.023 Y213.029 E2.99216 ; infill
M106 S244.8 ; enable fan
G1 Z3.850 F1800.000 ; move to next layer (3)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E3.01450 ; external small perimeter
G1 X191.769 Y208.626 E3.03683 ; external small perimeter
G1 X188.274 Y213.927 E3.05916 ; external small perimeter
G1 X181.935 Y213.552 E3.08150 ; external small perimeter
G1 X179.091 Y207.874 E3.10383 ; external small perimeter
G1 X182.487 Y202.723 E3.12553 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E3.14126 ; infill
G1 X183.792 Y203.532 E3.16019 ; infill
G1 X190.156 Y209.895 E3.21210 ; infill
G1 X188.932 Y211.752 E3.22492 ; infill
G1 X181.928 Y204.748 E3.28206 ; infill
G1 X180.704 Y206.605 E3.29488 ; infill
G1 X187.068 Y212.968 E3.34679 ; infill
G1 X183.793 Y212.774 E3.36572 ; infill
G1 X181.865 Y210.846 E3.38145 ; infill
M106 S242.25 ; enable fan
G1 Z5.050 F1800.000 ; move to next layer (4)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E3.40378 ; external small perimeter
G1 X191.769 Y208.626 E3.42611 ; external small perimeter
G1 X188.274 Y213.927 E3.44845 ; external small perimeter
G1 X181.935 Y213.552 E3.47078 ; external small perimeter
G1 X179.091 Y207.874 E3.49312 ; external small perimeter
G1 X182.487 Y202.723 E3.51482 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E3.52848 ; infill
G1 X180.157 Y208.503 E3.55159 ; infill
G1 X180.804 Y209.795 E3.55993 ; infill
G1 X186.944 Y203.655 E3.61002 ; infill
G1 X188.577 Y203.752 E3.61945 ; infill
G1 X189.028 Y204.652 E3.62526 ; infill
G1 X181.832 Y211.848 E3.68396 ; infill
G1 X182.283 Y212.748 E3.68976 ; infill
G1 X183.916 Y212.845 E3.69920 ; infill
G1 X190.056 Y206.705 E3.74928 ; infill
G1 X190.703 Y207.997 E3.75762 ; infill
G1 X188.498 Y211.343 E3.78074 ; infill
G1 X186.824 Y213.017 E3.79440 ; infill
M106 S244.8 ; enable fan
G1 Z6.250 F1800.000 ; move to next layer (5)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E3.81673 ; external small perimeter
G1 X191.769 Y208.626 E3.83906 ; external small perimeter
G1 X188.274 Y213.927 E3.86140 ; external small perimeter
G1 X181.935 Y213.552 E3.88373 ; external small perimeter
G1 X179.091 Y207.874 E3.90607 ; external small perimeter
G1 X182.487 Y202.723 E3.92777 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E3.94350 ; infill
G1 X183.792 Y203.532 E3.96242 ; infill
G1 X190.156 Y209.895 E4.01433 ; infill
G1 X188.932 Y211.752 E4.02716 ; infill
G1 X181.928 Y204.748 E4.08429 ; infill
G1 X180.704 Y206.605 E4.09712 ; infill
G1 X187.068 Y212.968 E4.14903 ; infill
G1 X183.793 Y212.774 E4.16795 ; infill
G1 X181.865 Y210.846 E4.18368 ; infill
M106 S242.25 ; enable fan
G1 Z7.450 F1800.000 ; move to next layer (6)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E4.20601 ; external small perimeter
G1 X191.769 Y208.626 E4.22835 ; external small perimeter
G1 X188.274 Y213.927 E4.25068 ; external small perimeter
G1 X181.935 Y213.552 E4.27302 ; external small perimeter
G1 X179.091 Y207.874 E4.29535 ; external small perimeter
G1 X182.487 Y202.723 E4.31705 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E4.33071 ; infill
G1 X180.157 Y208.503 E4.35382 ; infill
G1 X180.804 Y209.795 E4.36216 ; infill
G1 X186.944 Y203.655 E4.41225 ; infill
G1 X188.577 Y203.752 E4.42168 ; infill
G1 X189.028 Y204.652 E4.42749 ; infill
G1 X181.832 Y211.848 E4.48619 ; infill
G1 X182.283 Y212.748 E4.49200 ; infill
G1 X183.916 Y212.845 E4.50143 ; infill
G1 X190.056 Y206.705 E4.55152 ; infill
G1 X190.703 Y207.997 E4.55986 ; infill
G1 X188.498 Y211.343 E4.58297 ; infill
G1 X186.824 Y213.017 E4.59663 ; infill
M106 S244.8 ; enable fan
G1 Z8.650 F1800.000 ; move to next layer (7)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E4.61896 ; external small perimeter
G1 X191.769 Y208.626 E4.64130 ; external small perimeter
G1 X188.274 Y213.927 E4.66363 ; external small perimeter
G1 X181.935 Y213.552 E4.68597 ; external small perimeter
G1 X179.091 Y207.874 E4.70830 ; external small perimeter
G1 X182.487 Y202.723 E4.73000 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E4.74573 ; infill
G1 X183.792 Y203.532 E4.76465 ; infill
G1 X190.156 Y209.895 E4.81656 ; infill
G1 X188.932 Y211.752 E4.82939 ; infill
G1 X181.928 Y204.748 E4.88652 ; infill
G1 X180.704 Y206.605 E4.89935 ; infill
G1 X187.068 Y212.968 E4.95126 ; infill
G1 X183.793 Y212.774 E4.97018 ; infill
G1 X181.865 Y210.846 E4.98591 ; infill
M106 S242.25 ; enable fan
G1 Z9.850 F1800.000 ; move to next layer (8)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E5.00825 ; external small perimeter
G1 X191.769 Y208.626 E5.03058 ; external small perimeter
G1 X188.274 Y213.927 E5.05291 ; external small perimeter
G1 X181.935 Y213.552 E5.07525 ; external small perimeter
G1 X179.091 Y207.874 E5.09758 ; external small perimeter
G1 X182.487 Y202.723 E5.11928 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E5.13294 ; infill
G1 X180.157 Y208.503 E5.15606 ; infill
G1 X180.804 Y209.795 E5.16440 ; infill
G1 X186.944 Y203.655 E5.21448 ; infill
G1 X188.577 Y203.752 E5.22392 ; infill
G1 X189.028 Y204.652 E5.22972 ; infill
G1 X181.832 Y211.848 E5.28842 ; infill
G1 X182.283 Y212.748 E5.29423 ; infill
G1 X183.916 Y212.845 E5.30366 ; infill
G1 X190.056 Y206.705 E5.35375 ; infill
G1 X190.703 Y207.997 E5.36209 ; infill
G1 X188.498 Y211.343 E5.38520 ; infill
G1 X186.824 Y213.017 E5.39886 ; infill
M106 S244.8 ; enable fan
G1 Z11.050 F1800.000 ; move to next layer (9)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E5.42120 ; external small perimeter
G1 X191.769 Y208.626 E5.44353 ; external small perimeter
G1 X188.274 Y213.927 E5.46586 ; external small perimeter
G1 X181.935 Y213.552 E5.48820 ; external small perimeter
G1 X179.091 Y207.874 E5.51053 ; external small perimeter
G1 X182.487 Y202.723 E5.53223 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E5.54796 ; infill
G1 X183.792 Y203.532 E5.56688 ; infill
G1 X190.156 Y209.895 E5.61880 ; infill
G1 X188.932 Y211.752 E5.63162 ; infill
G1 X181.928 Y204.748 E5.68876 ; infill
G1 X180.704 Y206.605 E5.70158 ; infill
G1 X187.068 Y212.968 E5.75349 ; infill
G1 X183.793 Y212.774 E5.77242 ; infill
G1 X181.865 Y210.846 E5.78815 ; infill
M106 S242.25 ; enable fan
G1 Z12.250 F1800.000 ; move to next layer (10)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E5.81048 ; external small perimeter
G1 X191.769 Y208.626 E5.83281 ; external small perimeter
G1 X188.274 Y213.927 E5.85515 ; external small perimeter
G1 X181.935 Y213.552 E5.87748 ; external small perimeter
G1 X179.091 Y207.874 E5.89982 ; external small perimeter
G1 X182.487 Y202.723 E5.92152 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E5.93518 ; infill
G1 X180.157 Y208.503 E5.95829 ; infill
G1 X180.804 Y209.795 E5.96663 ; infill
G1 X186.944 Y203.655 E6.01672 ; infill
G1 X188.577 Y203.752 E6.02615 ; infill
G1 X189.028 Y204.652 E6.03196 ; infill
G1 X181.832 Y211.848 E6.09065 ; infill
G1 X182.283 Y212.748 E6.09646 ; infill
G1 X183.916 Y212.845 E6.10590 ; infill
G1 X190.056 Y206.705 E6.15598 ; infill
G1 X190.703 Y207.997 E6.16432 ; infill
G1 X188.498 Y211.343 E6.18744 ; infill
G1 X186.824 Y213.017 E6.20109 ; infill
M106 S244.8 ; enable fan
G1 Z13.450 F1800.000 ; move to next layer (11)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E6.22343 ; external small perimeter
G1 X191.769 Y208.626 E6.24576 ; external small perimeter
G1 X188.274 Y213.927 E6.26810 ; external small perimeter
G1 X181.935 Y213.552 E6.29043 ; external small perimeter
G1 X179.091 Y207.874 E6.31277 ; external small perimeter
G1 X182.487 Y202.723 E6.33447 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E6.35020 ; infill
G1 X183.792 Y203.532 E6.36912 ; infill
G1 X190.156 Y209.895 E6.42103 ; infill
G1 X188.932 Y211.752 E6.43386 ; infill
G1 X181.928 Y204.748 E6.49099 ; infill
G1 X180.704 Y206.605 E6.50382 ; infill
G1 X187.068 Y212.968 E6.55573 ; infill
G1 X183.793 Y212.774 E6.57465 ; infill
G1 X181.865 Y210.846 E6.59038 ; infill
M106 S242.25 ; enable fan
G1 Z14.650 F1800.000 ; move to next layer (12)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E6.61271 ; external small perimeter
G1 X191.769 Y208.626 E6.63505 ; external small perimeter
G1 X188.274 Y213.927 E6.65738 ; external small perimeter
G1 X181.935 Y213.552 E6.67972 ; external small perimeter
G1 X179.091 Y207.874 E6.70205 ; external small perimeter
G1 X182.487 Y202.723 E6.72375 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E6.73741 ; infill
G1 X180.157 Y208.503 E6.76052 ; infill
G1 X180.804 Y209.795 E6.76886 ; infill
G1 X186.944 Y203.655 E6.81895 ; infill
G1 X188.577 Y203.752 E6.82838 ; infill
G1 X189.028 Y204.652 E6.83419 ; infill
G1 X181.832 Y211.848 E6.89289 ; infill
G1 X182.283 Y212.748 E6.89870 ; infill
G1 X183.916 Y212.845 E6.90813 ; infill
G1 X190.056 Y206.705 E6.95822 ; infill
G1 X190.703 Y207.997 E6.96656 ; infill
G1 X188.498 Y211.343 E6.98967 ; infill
G1 X186.824 Y213.017 E7.00333 ; infill
M106 S244.8 ; enable fan
G1 Z15.850 F1800.000 ; move to next layer (13)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E7.02566 ; external small perimeter
G1 X191.769 Y208.626 E7.04800 ; external small perimeter
G1 X188.274 Y213.927 E7.07033 ; external small perimeter
G1 X181.935 Y213.552 E7.09266 ; external small perimeter
G1 X179.091 Y207.874 E7.11500 ; external small perimeter
G1 X182.487 Y202.723 E7.13670 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E7.15243 ; infill
G1 X183.792 Y203.532 E7.17135 ; infill
G1 X190.156 Y209.895 E7.22326 ; infill
G1 X188.932 Y211.752 E7.23609 ; infill
G1 X181.928 Y204.748 E7.29322 ; infill
G1 X180.704 Y206.605 E7.30605 ; infill
G1 X187.068 Y212.968 E7.35796 ; infill
G1 X183.793 Y212.774 E7.37688 ; infill
G1 X181.865 Y210.846 E7.39261 ; infill
M106 S242.25 ; enable fan
G1 Z17.050 F1800.000 ; move to next layer (14)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E7.41495 ; external small perimeter
G1 X191.769 Y208.626 E7.43728 ; external small perimeter
G1 X188.274 Y213.927 E7.45961 ; external small perimeter
G1 X181.935 Y213.552 E7.48195 ; external small perimeter
G1 X179.091 Y207.874 E7.50428 ; external small perimeter
G1 X182.487 Y202.723 E7.52598 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E7.53964 ; infill
G1 X180.157 Y208.503 E7.56276 ; infill
G1 X180.804 Y209.795 E7.57109 ; infill
G1 X186.944 Y203.655 E7.62118 ; infill
G1 X188.577 Y203.752 E7.63062 ; infill
G1 X189.028 Y204.652 E7.63642 ; infill
G1 X181.832 Y211.848 E7.69512 ; infill
G1 X182.283 Y212.748 E7.70093 ; infill
G1 X183.916 Y212.845 E7.71036 ; infill
G1 X190.056 Y206.705 E7.76045 ; infill
G1 X190.703 Y207.997 E7.76879 ; infill
G1 X188.498 Y211.343 E7.79190 ; infill
G1 X186.824 Y213.017 E7.80556 ; infill
M106 S244.8 ; enable fan
G1 Z18.250 F1800.000 ; move to next layer (15)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E7.82790 ; external small perimeter
G1 X191.769 Y208.626 E7.85023 ; external small perimeter
G1 X188.274 Y213.927 E7.87256 ; external small perimeter
G1 X181.935 Y213.552 E7.89490 ; external small perimeter
G1 X179.091 Y207.874 E7.91723 ; external small perimeter
G1 X182.487 Y202.723 E7.93893 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E7.95466 ; infill
G1 X183.792 Y203.532 E7.97358 ; infill
G1 X190.156 Y209.895 E8.02550 ; infill
G1 X188.932 Y211.752 E8.03832 ; infill
G1 X181.928 Y204.748 E8.09546 ; infill
G1 X180.704 Y206.605 E8.10828 ; infill
G1 X187.068 Y212.968 E8.16019 ; infill
G1 X183.793 Y212.774 E8.17911 ; infill
G1 X181.865 Y210.846 E8.19484 ; infill
M106 S242.25 ; enable fan
G1 Z19.450 F1800.000 ; move to next layer (16)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E8.21718 ; external small perimeter
G1 X191.769 Y208.626 E8.23951 ; external small perimeter
G1 X188.274 Y213.927 E8.26185 ; external small perimeter
G1 X181.935 Y213.552 E8.28418 ; external small perimeter
G1 X179.091 Y207.874 E8.30652 ; external small perimeter
G1 X182.487 Y202.723 E8.32822 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E8.34188 ; infill
G1 X180.157 Y208.503 E8.36499 ; infill
G1 X180.804 Y209.795 E8.37333 ; infill
G1 X186.944 Y203.655 E8.42342 ; infill
G1 X188.577 Y203.752 E8.43285 ; infill
G1 X189.028 Y204.652 E8.43866 ; infill
G1 X181.832 Y211.848 E8.49735 ; infill
G1 X182.283 Y212.748 E8.50316 ; infill
G1 X183.916 Y212.845 E8.51259 ; infill
G1 X190.056 Y206.705 E8.56268 ; infill
G1 X190.703 Y207.997 E8.57102 ; infill
G1 X188.498 Y211.343 E8.59414 ; infill
G1 X186.824 Y213.017 E8.60779 ; infill
M106 S244.8 ; enable fan
G1 Z20.650 F1800.000 ; move to next layer (17)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E8.63013 ; external small perimeter
G1 X191.769 Y208.626 E8.65246 ; external small perimeter
G1 X188.274 Y213.927 E8.67480 ; external small perimeter
G1 X181.935 Y213.552 E8.69713 ; external small perimeter
G1 X179.091 Y207.874 E8.71946 ; external small perimeter
G1 X182.487 Y202.723 E8.74117 ; external small perimeter
G1 X188.995 Y205.654 F1800.000 ; move to first infill point
G1 F600.000
G1 X187.067 Y203.726 E8.75690 ; infill
G1 X183.792 Y203.532 E8.77582 ; infill
G1 X190.156 Y209.895 E8.82773 ; infill
G1 X188.932 Y211.752 E8.84055 ; infill
G1 X181.928 Y204.748 E8.89769 ; infill
G1 X180.704 Y206.605 E8.91052 ; infill
G1 X187.068 Y212.968 E8.96243 ; infill
G1 X183.793 Y212.774 E8.98135 ; infill
G1 X181.865 Y210.846 E8.99708 ; infill
M106 S242.25 ; enable fan
G1 Z21.850 F1800.000 ; move to next layer (18)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E9.01941 ; external small perimeter
G1 X191.769 Y208.626 E9.04175 ; external small perimeter
G1 X188.274 Y213.927 E9.06408 ; external small perimeter
G1 X181.935 Y213.552 E9.08641 ; external small perimeter
G1 X179.091 Y207.874 E9.10875 ; external small perimeter
G1 X182.487 Y202.723 E9.13045 ; external small perimeter
G1 X184.036 Y203.483 F1800.000 ; move to first infill point
G1 F600.000
G1 X182.362 Y205.157 E9.14411 ; infill
G1 X180.157 Y208.503 E9.16722 ; infill
G1 X180.804 Y209.795 E9.17556 ; infill
G1 X186.944 Y203.655 E9.22565 ; infill
G1 X188.577 Y203.752 E9.23508 ; infill
G1 X189.028 Y204.652 E9.24089 ; infill
G1 X181.832 Y211.848 E9.29959 ; infill
G1 X182.283 Y212.748 E9.30539 ; infill
G1 X183.916 Y212.845 E9.31483 ; infill
G1 X190.056 Y206.705 E9.36492 ; infill
G1 X190.703 Y207.997 E9.37326 ; infill
G1 X188.498 Y211.343 E9.39637 ; infill
G1 X186.824 Y213.017 E9.41003 ; infill
M106 S249.9 ; enable fan
G1 Z23.050 F1800.000 ; move to next layer (19)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E9.43236 ; external small perimeter
G1 X191.769 Y208.626 E9.45470 ; external small perimeter
G1 X188.274 Y213.927 E9.47703 ; external small perimeter
G1 X181.935 Y213.552 E9.49936 ; external small perimeter
G1 X179.091 Y207.874 E9.52170 ; external small perimeter
G1 X182.487 Y202.723 E9.54340 ; external small perimeter
G1 X188.577 Y204.820 F1800.000 ; move to first infill point
G1 F1200.000
G1 X187.509 Y203.752 E9.55270 ; infill
G1 X184.713 Y203.586 E9.56995 ; infill
G1 X190.500 Y209.374 E9.62035 ; infill
G1 X189.454 Y210.959 E9.63205 ; infill
G1 X182.451 Y203.955 E9.69304 ; infill
G1 X181.406 Y205.541 E9.70474 ; infill
G1 X188.409 Y212.545 E9.76573 ; infill
G1 X188.090 Y213.029 E9.76930 ; infill
G1 X186.147 Y212.914 E9.78129 ; infill
G1 X180.360 Y207.126 E9.83169 ; infill
G1 X180.157 Y207.435 E9.83396 ; infill
G1 X182.283 Y211.680 E9.86320 ; infill
G1 X183.351 Y212.748 E9.87250 ; infill
G1 Z24.250 F1800.000 ; move to next layer (20)
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 F600.000
G1 X188.925 Y202.948 E9.89483 ; external small perimeter
G1 X191.769 Y208.626 E9.91717 ; external small perimeter
G1 X188.274 Y213.927 E9.93950 ; external small perimeter
G1 X181.935 Y213.552 E9.96183 ; external small perimeter
G1 X179.091 Y207.874 E9.98417 ; external small perimeter
G1 X182.487 Y202.723 E10.00587 ; external small perimeter
G1 X182.770 Y204.539 F1800.000 ; move to first infill point
G1 F1200.000
G1 X183.837 Y203.471 E10.01488 ; infill
G1 X186.243 Y203.614 E10.02925 ; infill
G1 X180.556 Y209.301 E10.07723 ; infill
G1 X181.407 Y210.999 E10.08856 ; infill
G1 X188.602 Y203.803 E10.14927 ; infill
G1 X189.453 Y205.501 E10.16060 ; infill
G1 X182.258 Y212.697 E10.22130 ; infill
G1 X182.283 Y212.748 E10.22164 ; infill
G1 X184.617 Y212.886 E10.23559 ; infill
G1 X190.304 Y207.199 E10.28357 ; infill
G1 X190.703 Y207.997 E10.28889 ; infill
G1 X188.091 Y211.961 E10.31721 ; infill
G1 X187.023 Y213.029 E10.32622 ; infill
M106 S237.15 ; enable fan
G1 Z25.450 F1800.000 ; move to next layer (21)
G1 E8.32622 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X182.586 Y202.573 F1800.000 ; move to first external small perimeter point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F600.000
G1 X188.925 Y202.948 E2.02233 ; external small perimeter
G1 X191.769 Y208.626 E2.04467 ; external small perimeter
G1 X188.274 Y213.927 E2.06700 ; external small perimeter
G1 X181.935 Y213.552 E2.08934 ; external small perimeter
G1 X179.091 Y207.874 E2.11167 ; external small perimeter
G1 X182.487 Y202.723 E2.13337 ; external small perimeter
G1 E0.13337 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
G1 X188.668 Y204.319 F1800.000 ; move to first infill point
G1 E2.00000 F2400.00000 ; unretract extruder 0
G1 F900.000
G1 X187.888 Y203.539 E2.00370 ; infill
G1 X186.364 Y203.449 E2.00883 ; infill
G1 X190.107 Y207.192 E2.02659 ; infill
G1 X190.986 Y208.946 E2.03318 ; infill
G1 X190.764 Y209.283 E2.03453 ; infill
G1 X184.840 Y203.359 E2.06265 ; infill
G1 X183.316 Y203.268 E2.06777 ; infill
G1 X190.194 Y210.147 E2.10042 ; infill
G1 X189.625 Y211.011 E2.10389 ; infill
G1 X182.375 Y203.761 E2.13830 ; infill
G1 X181.805 Y204.625 E2.14178 ; infill
G1 X189.055 Y211.875 E2.17619 ; infill
G1 X188.485 Y212.739 E2.17966 ; infill
G1 X181.235 Y205.489 E2.21407 ; infill
G1 X180.666 Y206.353 E2.21755 ; infill
G1 X187.544 Y213.232 E2.25020 ; infill
G1 X186.020 Y213.141 E2.25532 ; infill
G1 X180.096 Y207.217 E2.28344 ; infill
G1 X179.874 Y207.554 E2.28479 ; infill
G1 X180.753 Y209.308 E2.29137 ; infill
G1 X184.496 Y213.051 E2.30914 ; infill
G1 X182.972 Y212.961 E2.31426 ; infill
G1 X182.192 Y212.181 E2.31797 ; infill
G1 E0.31797 F2400.00000 ; retract extruder 0
G92 E0 ; reset extrusion distance
M107 ; disable fan
; Filament-specific end gcode 
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

M140 S0 ; set bed temperature
; cog_x = 185.444798
; cog_y = 208.264500
; cog_z = 13.274611
; filament_length_m = 0.0088 
; filament_volume_cm3 = 0.0625
; total_filament_cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_ears = 0
; brim_ears_max_angle = 125
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.0195
; fan_always_on = 0
; fan_below_layer_time = 60
; fan_percentage = 0
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 2
; first_layer_speed = 10
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 8
; toolchange_gcode = 
; travel_speed = 30
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = -0.1
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.35
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 58
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 2
; bridge_speed = 20
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 80%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 2
; infill_overlap = 55%
; infill_speed = 10
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 2
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3
